import {
  BarChart2,
  FileText,
  Mail,
  Briefcase,
  Mic,
  Download,
  Map,
  DollarSign,
  CheckSquare,
  Globe,
} from 'lucide-react'
import LinkedinIcon from '../icons/LinkedinIcon'

export const TOOLS = [
  {
    to: '/skill-gap',
    doneKey: 'skill_gap',
    icon: BarChart2,
    name: 'Skill Gap Analysis',
    description: 'See how you match your target role.',
    border: 'border-mint',
    text: 'text-mint',
  },
  {
    to: '/cv-analyser',
    doneKey: 'cv_analyser',
    icon: FileText,
    name: 'CV Analyser',
    description: 'Upload your CV for a structured review.',
    border: 'border-teal',
    text: 'text-teal',
  },
  {
    to: '/cover-letter',
    doneKey: 'cover_letter',
    icon: Mail,
    name: 'Cover Letter',
    description: 'Generate a tailored cover letter.',
    border: 'border-purple',
    text: 'text-purple',
  },
  {
    to: '/job-roles',
    doneKey: 'job_roles',
    icon: Briefcase,
    name: 'Job Role Suggestions',
    description: 'Roles to target now and in six months.',
    border: 'border-gold',
    text: 'text-gold',
  },
  {
    to: '/linkedin-message',
    doneKey: 'linkedin_message',
    icon: LinkedinIcon,
    name: 'LinkedIn Message',
    description: 'Draft a cold outreach message.',
    border: 'border-blue-600',
    text: 'text-blue-600',
  },
  {
    to: '/interview-prep',
    doneKey: 'interview_prep',
    icon: Mic,
    name: 'Interview Prep',
    description: 'Practice role-specific questions.',
    border: 'border-pink-600',
    text: 'text-pink-600',
  },
  {
    to: '/cv-download',
    doneKey: 'cv_download',
    icon: Download,
    name: 'CV Download',
    description: 'Get an ATS-friendly CV as a PDF.',
    border: 'border-cyan-600',
    text: 'text-cyan-600',
  },
  {
    to: '/career-roadmap',
    doneKey: 'career_roadmap',
    icon: Map,
    name: 'Career Roadmap',
    description: 'Milestones from now to one year out.',
    border: 'border-orange-600',
    text: 'text-orange-600',
  },
  {
    to: '/salary-insights',
    doneKey: 'salary_insights',
    icon: DollarSign,
    name: 'Salary Insights',
    description: 'Ranges and negotiation tips.',
    border: 'border-emerald-600',
    text: 'text-emerald-600',
  },
  {
    to: '/application-tracker',
    doneKey: 'application_tracker',
    icon: CheckSquare,
    name: 'Application Tracker',
    description: 'Track every application in one place.',
    border: 'border-indigo-600',
    text: 'text-indigo-600',
  },
  {
    to: '/cv-translator',
    doneKey: 'cv_translator',
    icon: Globe,
    name: 'CV Translator',
    description: 'Translate your CV into another language.',
    border: 'border-rose-600',
    text: 'text-rose-600',
  },
]
